os:
  editPreset: nvim
  readFromClipboardCmd: "pbpaste {{text}}"
  copyToClipboardCmd: pbcopy
git:
  localBranchSortOrder: recency
  paging:
    colorArg: always
    pager: delta --dark --paging=never
