os:
  editPreset: 'nvim'
  readFromClipboardCmd: 'pbpaste'
  # copyToClipboardCmd: 'pbcopy'
git:
  localBranchSortOrder: recency
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
